spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/events/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
#        - id: ticketing-service
#          uri: lb://ticketing-service
#          predicates:
#            - Path=/api/v1/tickets/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9090

eureka:
  instance:
    hostname: api-gateway
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
