spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/events/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
#        - id: ticketing-service
#          uri: lb://ticketing-service
#          predicates:
#            - Path=/api/v1/tickets/**
server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
