apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-service
  template:
    metadata:
      labels:
        app: ticketing-service
    spec:
      containers:
        - name: ticketing-service
          image: ticketing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-service
spec:
  type: ClusterIP
  selector:
    app: ticketing-service
  ports:
    - port: 8083
      targetPort: 8083

