server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://ticketing-db:5432/ticketing_db
    username: ticketuser
    password: ticketpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all

    properties:
      spring:
        json:
          trusted:
            packages: "com.event.management.ticketingservice.event"

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000


event-service:
  url: http://event-service:8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  paths-to-match: /api/v1/**
  writer-with-order-by-keys: true
  model-and-view-allowed: true
  show-actuator: true
  show-spring-cloud-configs: true
  override-with-rswag: false


eureka:
  instance:
    hostname: ticketing-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans