spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8761

eureka:
  instance:
    hostname: event-service
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
      enable-self-preservation: true
      eviction-interval-timer-in-ms: 25000
    prefer-ip-address: true